# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'descriptive_statistics'
gem 'shotgun'
gem 'sinatra'

group :development, :test do
  gem 'pry'
  gem 'pry-nav'
end
group :test do
  gem 'rspec'
  gem 'rubocop'
end
